pipeline:
  name: Build 1383051_Devops_Casestudy_Spring_app
  identifier: Build_1383051_Devops_Casestudy_Spring_app_1692461750656
  projectIdentifier: CISprigApp
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesHosted
            spec:
              identifier: k8s-hosted-infra
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    connectorRef: account.harnessImage
                    image: alpine
                    shell: Sh
                    command: echo "Welcome to Harness CI"
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.Github_OAuth_1692456884886
                    repoName: 1383051_Devops_Casestudy_Spring_app
                    build:
                      type: branch
                      spec:
                        branch: master
                  description: Cloning git branch
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1692456884886
        repoName: rahulkalithkar/1383051_Devops_Casestudy_Spring_app
        build: <+input>
